import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:speechmate/services/progress_service.dart';

class ReportGenerator {
  static Future<void> generateAndPrintReport(String studentName) async {
    final pdf = pw.Document();
    
    // Simulate fetching data for the student
    final ProgressService progress = ProgressService();
    final wordsLearned = await progress.getWordsLearnedCount();
    final streak = await progress.getStreak();
    final quizzes = await progress.getQuizScores();
    
    double averageScore = 0;
    if (quizzes.isNotEmpty) {
      int sum = 0;
      for(var score in quizzes) {
         final parts = score.split('/');
         if (parts.length == 2) {
           sum += int.parse(parts[0]);
         }
      }
      averageScore = (sum / quizzes.length) * 10; // assuming out of 10
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(20),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                   level: 0,
                   child: pw.Text("SpeechMate Parent Report Card", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800))
                ),
                pw.SizedBox(height: 20),
                pw.Text("Student Name: $studentName", style: pw.TextStyle(fontSize: 18)),
                pw.Text("Date: ${DateTime.now().toString().split(' ')[0]}", style: pw.TextStyle(color: PdfColors.grey600)),
                pw.Divider(color: PdfColors.teal200),
                pw.SizedBox(height: 30),
                
                pw.Text("Learning Metrics", style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                pw.SizedBox(height: 15),
                
                // Stats Table
                pw.Table.fromTextArray(
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.teal600),
                  cellHeight: 30,
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.center,
                  },
                  headers: <String>['Metric', 'Value'],
                  data: <List<String>>[
                    ['Words Mastered', '$wordsLearned / 100+'],
                    ['Current Learning Streak', '$streak Days'],
                    ['Quizzes Completed', '${quizzes.length}'],
                    ['Average Quiz Score', '${averageScore.toStringAsFixed(1)}%'],
                  ],
                ),
                
                pw.SizedBox(height: 40),
                
                // Progress Chart / Baseline vs Current (Mocked for visual)
                pw.Text("Performance Overview", style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                pw.SizedBox(height: 10),
                pw.Text(
                   "This chart demonstrates the student's improvement since their baseline assessment. "
                   "Continued use of SpeechMate's Spaced Repetition System has resulted in steady vocabulary growth.",
                   style: const pw.TextStyle(fontSize: 12)
                ),
                pw.SizedBox(height: 20),
                
                // A primitive bar chart representation using containers
                pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    _buildBar("Baseline\nStart", 30, PdfColors.red400),
                    pw.SizedBox(width: 40),
                    _buildBar("Mid-Term", 55, PdfColors.orange400),
                    pw.SizedBox(width: 40),
                    _buildBar("Current", 85, PdfColors.green400),
                  ]
                ),
                
                pw.Spacer(),
                pw.Divider(color: PdfColors.grey400),
                pw.SizedBox(height: 10),
                pw.Text("Generated by SpeechMate - Empowering Nicobarese Tribal Education", style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic), textAlign: pw.TextAlign.center),
              ]
            )
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: '${studentName}_SpeechMate_Report.pdf',
    );
  }

  static pw.Widget _buildBar(String label, double heightPerc, PdfColor color) {
    return pw.Column(
      children: [
         pw.Text("${heightPerc.toInt()}%", style: const pw.TextStyle(fontSize: 10)),
         pw.SizedBox(height: 5),
         pw.Container(
           width: 60,
           height: heightPerc * 2, // arbitrary scaling for visual
           color: color,
         ),
         pw.SizedBox(height: 5),
         pw.Text(label, style: const pw.TextStyle(fontSize: 10), textAlign: pw.TextAlign.center),
      ]
    );
  }
}
