import 'package:shared_preferences/shared_preferences.dart';

/// Central localization service for SpeechMate.
/// Reads the user's language preference from SharedPreferences
/// and returns the matching string map.
class AppStrings {
  static String _currentLang = 'en';

  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('language') ?? 'en';
  }

  static String get currentLanguage => _currentLang;

  static String get(String key) {
    final map = _allStrings[_currentLang] ?? _allStrings['en']!;
    return map[key] ?? _allStrings['en']![key] ?? key;
  }

  // ─────────────────────────────────────────────
  // Master String Table
  // ─────────────────────────────────────────────
  static final Map<String, Map<String, String>> _allStrings = {
    'en': _en,
    'hi': _hi,
    'ta': _ta,
    'ml': _ml,
    'bn': _bn,
    'te': _te,
    'gn': _gn,
    'nc': _nc,
  };

  // ═══════════════════════════════════════════════
  // ENGLISH
  // ═══════════════════════════════════════════════
  static final Map<String, String> _en = {
    // App-wide
    'appName': 'SpeechMate',
    'tagline': 'Where Language Barriers End',

    // Landing Page
    'youAre': 'You are:',
    'student': 'Student',
    'teacher': 'Teacher',
    'continueBtn': 'Continue',
    'guest': 'Guest',

    // Language Selection
    'selectLanguage': 'Select a Language to translate/learn',
    'selectAppLanguage': 'Select App Language',
    'comingSoon': '*More languages coming soon',
    'uiUpdateNote': '*UI texts will be updated dynamically in a future update.',

    // Student Dashboard
    'dailyReview': 'Daily Review',
    'jungleAdventure': 'Jungle Adventure',
    'islandColors': 'Island Colors',
    'numbers': 'Numbers',
    'nature': 'Nature',
    'feelings': 'Feelings',
    'colors': 'Colors',
    'animals': 'Animals',
    'family': 'Family',
    'bodyParts': 'Body Parts',
    'things': 'Things',
    'magicWords': 'Magic Words',
    'games': 'Games',
    'community': 'Community',
    'voiceVault': 'Voice Vault',
    'feedback': 'Feedback',
    'chatTranslate': ' Chat & Translate',
    'commonPhrases': 'Common Phrases',
    'dialects': 'Dialects',
    'search': 'Search',

    // Teacher Dashboard
    'quiz': 'Quiz',
    'progress': 'Progress',
    'generateReport': 'Generate Report',
    'levels': 'Levels',
    'lessons': 'Lessons',

    // Progress
    'yourProgress': 'Your Progress',
    'totalSearches': 'Total Searches',
    'currentStreak': 'Current Streak',
    'wordsLearned': 'Words Learned',
    'recentQuiz': '📊 Recent Quiz Performance',
    'noQuizzes': 'No quizzes completed yet. Start learning!',
    'quizAccuracy': 'Quiz Accuracy',

    // AI Assistant
    'tapMicToRecord': 'Tap mic to record',
    'recordingAudio': 'Recording audio... (Offline)',
    'transcribingWhisper': 'Transcribing with Whisper AI...',
    'tapMicToAsk': 'Tap the mic to ask something!',

    // SRS Review
    'srsTitle': 'Daily Review',
    'again': 'Again',
    'hard': 'Hard',
    'good': 'Good',
    'easy': 'Easy',
    'noCardsToday': 'No cards to review today! 🎉',
    'showAnswer': 'Show Answer',

    // General
    'goBack': 'Go Back',
    'days': 'days',
  };

  // ═══════════════════════════════════════════════
  // HINDI (हिंदी)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _hi = {
    'appName': 'स्पीचमेट',
    'tagline': 'जहाँ भाषा की बाधाएँ समाप्त होती हैं',
    'youAre': 'आप हैं:',
    'student': 'छात्र',
    'teacher': 'शिक्षक',
    'continueBtn': 'जारी रखें',
    'guest': 'अतिथि',
    'selectLanguage': 'अनुवाद/सीखने के लिए एक भाषा चुनें',
    'selectAppLanguage': 'ऐप भाषा चुनें',
    'comingSoon': '*और भाषाएँ जल्द आ रही हैं',
    'uiUpdateNote': '*UI भाषा भविष्य में अपडेट होगी।',
    'dailyReview': 'दैनिक समीक्षा',
    'jungleAdventure': 'जंगल साहसिक',
    'islandColors': 'द्वीप के रंग',
    'numbers': 'संख्याएँ',
    'nature': 'प्रकृति',
    'feelings': 'भावनाएँ',
    'colors': 'रंग',
    'animals': 'जानवर',
    'family': 'परिवार',
    'bodyParts': 'शरीर के अंग',
    'things': 'चीज़ें',
    'magicWords': 'जादुई शब्द',
    'games': 'खेल',
    'community': 'समुदाय',
    'voiceVault': 'ध्वनि संग्रह',
    'feedback': 'प्रतिक्रिया',
    'chatTranslate': 'चैट और अनुवाद',
    'commonPhrases': 'सामान्य वाक्यांश',
    'dialects': 'बोलियाँ',
    'search': 'खोजें',
    'quiz': 'प्रश्नोत्तरी',
    'progress': 'प्रगति',
    'generateReport': 'रिपोर्ट बनाएं',
    'levels': 'स्तर',
    'lessons': 'पाठ',
    'yourProgress': 'आपकी प्रगति',
    'totalSearches': 'कुल खोजें',
    'currentStreak': 'वर्तमान लकीर',
    'wordsLearned': 'सीखे गए शब्द',
    'recentQuiz': '📊 हालिया प्रश्नोत्तरी प्रदर्शन',
    'noQuizzes': 'अभी तक कोई प्रश्नोत्तरी पूरी नहीं हुई। सीखना शुरू करें!',
    'quizAccuracy': 'प्रश्नोत्तरी सटीकता',
    'tapMicToRecord': 'रिकॉर्ड करने के लिए माइक दबाएं',
    'recordingAudio': 'ऑडियो रिकॉर्ड हो रहा है... (ऑफ़लाइन)',
    'transcribingWhisper': 'विस्पर AI से लिखा जा रहा है...',
    'tapMicToAsk': 'कुछ पूछने के लिए माइक दबाएं!',
    'srsTitle': 'दैनिक समीक्षा',
    'again': 'फिर से',
    'hard': 'कठिन',
    'good': 'अच्छा',
    'easy': 'आसान',
    'noCardsToday': 'आज कोई कार्ड नहीं! 🎉',
    'showAnswer': 'उत्तर दिखाएं',
    'goBack': 'वापस जाएं',
    'days': 'दिन',
  };

  // ═══════════════════════════════════════════════
  // TAMIL (தமிழ்)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _ta = {
    'appName': 'ஸ்பீச்மேட்',
    'tagline': 'மொழி தடைகள் முடியும் இடம்',
    'youAre': 'நீங்கள்:',
    'student': 'மாணவர்',
    'teacher': 'ஆசிரியர்',
    'continueBtn': 'தொடரவும்',
    'guest': 'விருந்தினர்',
    'selectLanguage': 'மொழிபெயர்க்க/கற்க ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
    'selectAppLanguage': 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    'comingSoon': '*மேலும் மொழிகள் விரைவில்',
    'uiUpdateNote': '*UI உரைகள் எதிர்கால புதுப்பிப்பில் மாற்றப்படும்.',
    'dailyReview': 'தினசரி மதிப்பாய்வு',
    'jungleAdventure': 'காட்டு சாகசம்',
    'islandColors': 'தீவு நிறங்கள்',
    'numbers': 'எண்கள்',
    'nature': 'இயற்கை',
    'feelings': 'உணர்வுகள்',
    'colors': 'நிறங்கள்',
    'animals': 'விலங்குகள்',
    'family': 'குடும்பம்',
    'bodyParts': 'உடல் பாகங்கள்',
    'things': 'பொருட்கள்',
    'magicWords': 'மந்திர வார்த்தைகள்',
    'games': 'விளையாட்டுகள்',
    'community': 'சமூகம்',
    'voiceVault': 'குரல் பெட்டகம்',
    'feedback': 'கருத்து',
    'chatTranslate': 'அரட்டை & மொழிபெயர்க்க',
    'commonPhrases': 'பொதுவான சொற்றொடர்கள்',
    'dialects': 'வட்டார மொழிகள்',
    'search': 'தேடு',
    'quiz': 'வினாடி வினா',
    'progress': 'முன்னேற்றம்',
    'generateReport': 'அறிக்கை உருவாக்கு',
    'levels': 'நிலைகள்',
    'lessons': 'பாடங்கள்',
    'yourProgress': 'உங்கள் முன்னேற்றம்',
    'totalSearches': 'மொத்த தேடல்கள்',
    'currentStreak': 'தற்போதைய தொடர்',
    'wordsLearned': 'கற்ற சொற்கள்',
    'recentQuiz': '📊 சமீபத்திய வினாடி வினா செயல்திறன்',
    'noQuizzes': 'இன்னும் வினாடி வினா முடிக்கவில்லை. கற்கத் தொடங்குங்கள்!',
    'quizAccuracy': 'வினாடி வினா துல்லியம்',
    'tapMicToRecord': 'பதிவு செய்ய மைக்கை தட்டவும்',
    'recordingAudio': 'ஒலி பதிவாகிறது... (ஆஃப்லைன்)',
    'transcribingWhisper': 'விஸ்பர் AI மூலம் எழுதப்படுகிறது...',
    'tapMicToAsk': 'கேட்க மைக்கை தட்டவும்!',
    'srsTitle': 'தினசரி மதிப்பாய்வு',
    'again': 'மீண்டும்',
    'hard': 'கடினம்',
    'good': 'நல்லது',
    'easy': 'எளிது',
    'noCardsToday': 'இன்று அட்டைகள் இல்லை! 🎉',
    'showAnswer': 'பதிலைக் காட்டு',
    'goBack': 'திரும்பிச் செல்',
    'days': 'நாட்கள்',
  };

  // ═══════════════════════════════════════════════
  // MALAYALAM (മലയാളം)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _ml = {
    'appName': 'സ്പീച്ച്‌മേറ്റ്',
    'tagline': 'ഭാഷാ തടസ്സങ്ങൾ അവസാനിക്കുന്നിടം',
    'youAre': 'നിങ്ങൾ:',
    'student': 'വിദ്യാർത്ഥി',
    'teacher': 'അധ്യാപകൻ',
    'continueBtn': 'തുടരുക',
    'guest': 'അതിഥി',
    'selectLanguage': 'വിവർത്തനം/പഠിക്കാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    'selectAppLanguage': 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    'comingSoon': '*കൂടുതൽ ഭാഷകൾ ഉടൻ',
    'uiUpdateNote': '*UI ടെക്‌സ്‌റ്റുകൾ ഭാവിയിലെ അപ്‌ഡേറ്റിൽ മാറും.',
    'dailyReview': 'ദൈനംദിന അവലോകനം',
    'jungleAdventure': 'കാട്ടിലെ സാഹസികത',
    'islandColors': 'ദ്വീപ് നിറങ്ങൾ',
    'numbers': 'സംഖ്യകൾ',
    'nature': 'പ്രകൃതി',
    'feelings': 'വികാരങ്ങൾ',
    'colors': 'നിറങ്ങൾ',
    'animals': 'മൃഗങ്ങൾ',
    'family': 'കുടുംബം',
    'bodyParts': 'ശരീര ഭാഗങ്ങൾ',
    'things': 'വസ്‌തുക്കൾ',
    'magicWords': 'മാന്ത്രിക വാക്കുകൾ',
    'games': 'കളികൾ',
    'community': 'കമ്മ്യൂണിറ്റി',
    'voiceVault': 'ശബ്ദ ശേഖരം',
    'feedback': 'ഫീഡ്‌ബാക്ക്',
    'chatTranslate': 'ചാറ്റ് & വിവർത്തനം',
    'commonPhrases': 'സാധാരണ ശൈലികൾ',
    'dialects': 'ഉപഭാഷകൾ',
    'search': 'തിരയുക',
    'quiz': 'ക്വിസ്',
    'progress': 'പുരോഗതി',
    'generateReport': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    'levels': 'ലെവലുകൾ',
    'lessons': 'പാഠങ്ങൾ',
    'yourProgress': 'നിങ്ങളുടെ പുരോഗതി',
    'totalSearches': 'ആകെ തിരയലുകൾ',
    'currentStreak': 'നിലവിലെ സ്‌ട്രീക്ക്',
    'wordsLearned': 'പഠിച്ച വാക്കുകൾ',
    'recentQuiz': '📊 സമീപകാല ക്വിസ് പ്രകടനം',
    'noQuizzes': 'ഇതുവരെ ക്വിസ് പൂർത്തിയാക്കിയിട്ടില്ല. പഠിക്കാൻ തുടങ്ങൂ!',
    'quizAccuracy': 'ക്വിസ് കൃത്യത',
    'tapMicToRecord': 'റെക്കോർഡ് ചെയ്യാൻ മൈക്ക് ടാപ്പ് ചെയ്യുക',
    'recordingAudio': 'ഓഡിയോ റെക്കോർഡ് ചെയ്യുന്നു... (ഓഫ്‌ലൈൻ)',
    'transcribingWhisper': 'വിസ്‌പർ AI ഉപയോഗിച്ച് ട്രാൻസ്ക്രൈബ് ചെയ്യുന്നു...',
    'tapMicToAsk': 'എന്തെങ്കിലും ചോദിക്കാൻ മൈക്ക് ടാപ്പ് ചെയ്യുക!',
    'srsTitle': 'ദൈനംദിന അവലോകനം',
    'again': 'വീണ്ടും',
    'hard': 'കഠിനം',
    'good': 'നല്ലത്',
    'easy': 'എളുപ്പം',
    'noCardsToday': 'ഇന്ന് കാർഡുകൾ ഇല്ല! 🎉',
    'showAnswer': 'ഉത്തരം കാണിക്കുക',
    'goBack': 'തിരിച്ചുപോകുക',
    'days': 'ദിവസങ്ങൾ',
  };

  // ═══════════════════════════════════════════════
  // BENGALI (বাংলা)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _bn = {
    'appName': 'স্পিচমেট',
    'tagline': 'যেখানে ভাষার বাধা শেষ হয়',
    'youAre': 'আপনি হলেন:',
    'student': 'শিক্ষার্থী',
    'teacher': 'শিক্ষক',
    'continueBtn': 'চালিয়ে যান',
    'guest': 'অতিথি',
    'selectLanguage': 'অনুবাদ/শেখার জন্য একটি ভাষা নির্বাচন করুন',
    'selectAppLanguage': 'অ্যাপের ভাষা নির্বাচন করুন',
    'comingSoon': '*আরও ভাষা শীঘ্রই আসছে',
    'uiUpdateNote': '*UI পাঠ্য ভবিষ্যতে আপডেট হবে।',
    'dailyReview': 'দৈনিক পর্যালোচনা',
    'jungleAdventure': 'জঙ্গল অ্যাডভেঞ্চার',
    'islandColors': 'দ্বীপের রঙ',
    'numbers': 'সংখ্যা',
    'nature': 'প্রকৃতি',
    'feelings': 'অনুভূতি',
    'colors': 'রঙ',
    'animals': 'পশুপাখি',
    'family': 'পরিবার',
    'bodyParts': 'শরীরের অংশ',
    'things': 'জিনিসপত্র',
    'magicWords': 'জাদু শব্দ',
    'games': 'খেলা',
    'community': 'সম্প্রদায়',
    'voiceVault': 'ভয়েস ভল্ট',
    'feedback': 'মতামত',
    'chatTranslate': 'চ্যাট ও অনুবাদ',
    'commonPhrases': 'সাধারণ বাক্যাংশ',
    'dialects': 'উপভাষা',
    'search': 'অনুসন্ধান',
    'quiz': 'কুইজ',
    'progress': 'অগ্রগতি',
    'generateReport': 'রিপোর্ট তৈরি করুন',
    'levels': 'স্তর',
    'lessons': 'পাঠ',
    'yourProgress': 'আপনার অগ্রগতি',
    'totalSearches': 'মোট অনুসন্ধান',
    'currentStreak': 'বর্তমান ধারা',
    'wordsLearned': 'শেখা শব্দ',
    'recentQuiz': '📊 সাম্প্রতিক কুইজ পারফরম্যান্স',
    'noQuizzes': 'এখনও কোনো কুইজ সম্পন্ন হয়নি। শেখা শুরু করুন!',
    'quizAccuracy': 'কুইজ নির্ভুলতা',
    'tapMicToRecord': 'রেকর্ড করতে মাইক ট্যাপ করুন',
    'recordingAudio': 'অডিও রেকর্ড হচ্ছে... (অফলাইন)',
    'transcribingWhisper': 'হুইসপার AI দিয়ে লেখা হচ্ছে...',
    'tapMicToAsk': 'কিছু জিজ্ঞাসা করতে মাইক ট্যাপ করুন!',
    'srsTitle': 'দৈনিক পর্যালোচনা',
    'again': 'আবার',
    'hard': 'কঠিন',
    'good': 'ভালো',
    'easy': 'সহজ',
    'noCardsToday': 'আজ কোনো কার্ড নেই! 🎉',
    'showAnswer': 'উত্তর দেখান',
    'goBack': 'ফিরে যান',
    'days': 'দিন',
  };

  // ═══════════════════════════════════════════════
  // TELUGU (తెలుగు)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _te = {
    'appName': 'స్పీచ్‌మేట్',
    'tagline': 'భాషా అడ్డంకులు ముగిసే చోటు',
    'youAre': 'మీరు:',
    'student': 'విద్యార్థి',
    'teacher': 'ఉపాధ్యాయుడు',
    'continueBtn': 'కొనసాగించు',
    'guest': 'అతిథి',
    'selectLanguage': 'అనువాదం/నేర్చుకోవడానికి ఒక భాషను ఎంచుకోండి',
    'selectAppLanguage': 'యాప్ భాషను ఎంచుకోండి',
    'comingSoon': '*మరిన్ని భాషలు త్వరలో',
    'uiUpdateNote': '*UI వచనాలు భవిష్యత్ అప్‌డేట్‌లో మారుతాయి.',
    'dailyReview': 'రోజువారీ సమీక్ష',
    'jungleAdventure': 'అడవి సాహసం',
    'islandColors': 'దీవి రంగులు',
    'numbers': 'సంఖ్యలు',
    'nature': 'ప్రకృతి',
    'feelings': 'భావాలు',
    'colors': 'రంగులు',
    'animals': 'జంతువులు',
    'family': 'కుటుంబం',
    'bodyParts': 'శరీర భాగాలు',
    'things': 'వస్తువులు',
    'magicWords': 'మంత్ర పదాలు',
    'games': 'ఆటలు',
    'community': 'సమాజం',
    'voiceVault': 'వాయిస్ వాల్ట్',
    'feedback': 'అభిప్రాయం',
    'chatTranslate': 'చాట్ & అనువాదం',
    'commonPhrases': 'సాధారణ పదబంధాలు',
    'dialects': 'మాండలికాలు',
    'search': 'వెతుకు',
    'quiz': 'క్విజ్',
    'progress': 'పురోగతి',
    'generateReport': 'రిపోర్ట్ తయారు చేయండి',
    'levels': 'స్థాయిలు',
    'lessons': 'పాఠాలు',
    'yourProgress': 'మీ పురోగతి',
    'totalSearches': 'మొత్తం శోధనలు',
    'currentStreak': 'ప్రస్తుత స్ట్రీక్',
    'wordsLearned': 'నేర్చుకున్న పదాలు',
    'recentQuiz': '📊 ఇటీవలి క్విజ్ ప్రదర్శన',
    'noQuizzes': 'ఇంకా క్విజ్‌లు పూర్తి కాలేదు. నేర్చుకోవడం ప్రారంభించండి!',
    'quizAccuracy': 'క్విజ్ ఖచ్చితత్వం',
    'tapMicToRecord': 'రికార్డ్ చేయడానికి మైక్ నొక్కండి',
    'recordingAudio': 'ఆడియో రికార్డ్ అవుతోంది... (ఆఫ్‌లైన్)',
    'transcribingWhisper': 'విస్పర్ AI ద్వారా రాయబడుతోంది...',
    'tapMicToAsk': 'ఏదైనా అడగడానికి మైక్ నొక్కండి!',
    'srsTitle': 'రోజువారీ సమీక్ష',
    'again': 'మళ్ళీ',
    'hard': 'కష్టం',
    'good': 'బాగుంది',
    'easy': 'సులభం',
    'noCardsToday': 'ఈరోజు కార్డులు లేవు! 🎉',
    'showAnswer': 'సమాధానం చూపించు',
    'goBack': 'వెనక్కి వెళ్ళు',
    'days': 'రోజులు',
  };

  // ═══════════════════════════════════════════════
  // GREAT ANDAMANESE (gn)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _gn = {
    'appName': 'Speecho', // Placeholders until native community consensus
    'tagline': 'Julu boi-jio',
    'youAre': 'Ngiyo:',
    'student': 'Utire',
    'teacher': 'Oko-jumu',
    'continueBtn': 'Kato',
    'guest': 'Ep',
    'selectLanguage': 'Julu aka',
    'selectAppLanguage': 'Aka-julu yop',
    'dailyReview': 'Tare-tare',
    'jungleAdventure': 'Erem-toro',
    'islandColors': 'Tobo-chiro',
    'community': 'Oko-tolo',
    'voiceVault': 'Puchh-toro',
    'search': 'Koyo',
    'quiz': 'Boi-toro',
    'yourProgress': 'Ngiyo kolo',
    'tapMicToRecord': 'Mic e-koyo',
    'recordingAudio': 'Puchh...',
    'srsTitle': 'Tare',
    'showAnswer': 'E-koyo',
    'goBack': 'Tech-chi',
    'audioFirstDash': 'Puchh-Julu', // Audio-First Mode
  };

  // ═══════════════════════════════════════════════
  // NICOBARESE - CAR (nc)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _nc = {
    'appName': 'SpeechMate',
    'tagline': 'Rinön pö yök',
    'youAre': 'Cö:',
    'student': 'Kunö',
    'teacher': 'Ukuvöt',
    'continueBtn': 'Lökh',
    'guest': 'Kamyō',
    'selectLanguage': 'Hol yök',
    'selectAppLanguage': 'Hol yök app',
    'dailyReview': 'Inrē lūm',
    'jungleAdventure': 'Tōt',
    'islandColors': 'Pū-cö',
    'community': 'In-yū',
    'voiceVault': 'Ngō-in',
    'search': 'Hol',
    'quiz': 'U-in',
    'yourProgress': 'Cö lūm',
    'tapMicToRecord': 'Mic tōt',
    'recordingAudio': 'Ngō...',
    'srsTitle': 'Lūm',
    'showAnswer': 'Yök in',
    'goBack': 'Hol back',
    'audioFirstDash': 'Ngō-Inrē', // Audio-First Mode
  };
}
