import 'package:shared_preferences/shared_preferences.dart';

/// Central localization service for SpeechMate.
/// Reads the user's language preference from SharedPreferences
/// and returns the matching string map.
class AppStrings {
  static String _currentLang = 'en';

  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString('language') ?? 'en';
  }

  static String get currentLanguage => _currentLang;

  static String get(String key) {
    final map = _allStrings[_currentLang] ?? _allStrings['en']!;
    return map[key] ?? _allStrings['en']![key] ?? key;
  }

  // ─────────────────────────────────────────────
  // Master String Table
  // ─────────────────────────────────────────────
  static final Map<String, Map<String, String>> _allStrings = {
    'en': _en,
    'hi': _hi,
    'ta': _ta,
    'ml': _ml,
    'bn': _bn,
    'te': _te,
    'gn': _gn,
    'nc': _nc,
  };

  // ═══════════════════════════════════════════════
  // ENGLISH
  // ═══════════════════════════════════════════════
  static final Map<String, String> _en = {
    // App-wide
    'appName': 'SpeechMate',
    'tagline': 'Where Language Barriers End',

    // Landing Page
    'youAre': 'You are:',
    'student': 'Student',
    'teacher': 'Teacher',
    'continueBtn': 'Continue',
    'guest': 'Guest',

    // Language Selection
    'selectLanguage': 'Select a Language to translate/learn',
    'selectAppLanguage': 'Select App Language',
    'comingSoon': '*More languages coming soon',
    'uiUpdateNote': '*UI texts will be updated dynamically in a future update.',

    // Student Dashboard
    'dailyReview': 'Daily Review',
    'jungleAdventure': 'Jungle Adventure',
    'islandColors': 'Island Colors',
    'numbers': 'Numbers',
    'nature': 'Nature',
    'feelings': 'Feelings',
    'colors': 'Colors',
    'animals': 'Animals',
    'family': 'Family',
    'bodyParts': 'Body Parts',
    'things': 'Things',
    'magicWords': 'Magic Words',
    'games': 'Games',
    'community': 'Community',
    'voiceVault': 'Voice Vault',
    'feedback': 'Feedback',
    'chatTranslate': ' Chat & Translate',
    'commonPhrases': 'Common Phrases',
    'dialects': 'Dialects',
    'search': 'Search',

    // Teacher Dashboard
    'quiz': 'Quiz',
    'progress': 'Progress',
    'generateReport': 'Generate Report',
    'levels': 'Levels',
    'lessons': 'Lessons',

    // Progress
    'yourProgress': 'Your Progress',
    'totalSearches': 'Total Searches',
    'currentStreak': 'Current Streak',
    'wordsLearned': 'Words Learned',
    'recentQuiz': '📊 Recent Quiz Performance',
    'noQuizzes': 'No quizzes completed yet. Start learning!',
    'quizAccuracy': 'Quiz Accuracy',

    // AI Assistant
    'tapMicToRecord': 'Tap mic to record',
    'recordingAudio': 'Recording audio... (Offline)',
    'transcribingWhisper': 'Transcribing with Whisper AI...',
    'tapMicToAsk': 'Tap the mic to ask something!',

    // SRS Review
    'srsTitle': 'Daily Review',
    'again': 'Again',
    'hard': 'Hard',
    'good': 'Good',
    'easy': 'Easy',
    'noCardsToday': 'No cards to review today! 🎉',
    'showAnswer': 'Show Answer',

    // General
    'goBack': 'Go Back',
    'days': 'days',

    // New additions for full localization
    'arTranslator': 'AR Translator 📸',
    'bookScanner': 'Book Scanner',
    'voiceTranslate': 'Voice Translate',
    'andamaneseBeta': 'Andamanese ᴮᴱᵀᴬ',
    'natureHub': 'Nature Hub',
    'oralHistory': 'Oral History',
    'tuhetKinship': 'Tuhet (Kinship)',
    'islandExplorer': 'Island Explorer',
    'memoryPalace': 'Memory Palace',
    'exploreModules': 'Explore Modules',
    'seniorStudentAccess': 'Senior Student Access',
    'solveToEnter': 'Solve this to enter:\n12 + 15 = ?',
    'cancel': 'Cancel',
    'enter': 'Enter',
    'incorrectAccessDenied': 'Incorrect. Access Denied 🚫',
    'classroomTools': 'CLASSROOM TOOLS',
    'learningTools': 'LEARNING TOOLS',
    'communitySettings': 'COMMUNITY & SETTINGS',
    'dictEditor': 'Dict Editor',
    'importVocab': 'Import Vocab',
    'textTranslator': 'Text Translator',
    'culture': 'Culture',
    'certification': 'Certification',
    'quizMode': 'Quiz Mode',
    'srsAnalytics': 'SRS Analytics',
    'dialectComparison': 'Dialect Comparison',
    'islandGis': 'Island GIS',
    'tuhetMapper': 'Tuhet Mapper',
    'villageHub': 'Village Hub',
    'whisperPro': 'Whisper Pro',
    'betaChat': 'Beta Chat',
    'exportVocab': 'Export Vocab',
    'dailyWord': 'DAILY WORD',

    // Student Dashboard UI (section headers, pet, mission)
    'omniBroadcast': 'Omni Broadcast',
    'hindiTranslator': 'Hindi\nTranslator',
    'tamilTranslator': 'Tamil\nTranslator',
    'bengaliTranslator': 'Bengali\nTranslator',
    'teluguTranslator': 'Telugu\nTranslator',
    'malayalamTranslator': 'Malayalam\nTranslator',
    'aiSetup': 'AI Setup',
    'sectionSoundWave': 'Sound Wave',
    'sectionMyProgress': 'My Progress',
    'sectionMyBadges': 'My Badges',
    'sectionLetsLearn': "Let's Learn!",
    'dailyMission': 'DAILY MISSION',
    'missionHint': 'Use the AR Scanner or Games to explore words 🌟',
    'percentDone': 'done!',
    'petHappySpeech': "Yay! Let's learn! 🌟",
    'streakLabel': 'Streak',
    'starsLabel': 'Stars',
    'levelLabel': 'Level',
    // Mission texts
    'missionLearnWords': 'Learn 5 new Nicobarese words!',
    'missionPlayGames': 'Play 2 word games!',
    'missionScanAR': 'Scan 3 objects with AR!',
    'missionRecordVoice': 'Record 3 voice translations!',
    'missionBodyQuiz': 'Complete 1 body parts quiz!',
    'missionAnimals': 'Explore 4 animal words!',
    'missionNature': 'Learn 3 nature words!',
    'missionNumbers': 'Practice 5 number words!',
    'missionStories': 'Listen to 1 oral history!',
    'missionColors': 'Translate 4 color words!',
  };

  // ═══════════════════════════════════════════════
  // HINDI (हिंदी)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _hi = {
    'appName': 'स्पीचमेट',
    'tagline': 'जहाँ भाषा की बाधाएँ समाप्त होती हैं',
    'youAre': 'आप हैं:',
    'student': 'छात्र',
    'teacher': 'शिक्षक',
    'continueBtn': 'जारी रखें',
    'guest': 'अतिथि',
    'selectLanguage': 'अनुवाद/सीखने के लिए एक भाषा चुनें',
    'selectAppLanguage': 'ऐप भाषा चुनें',
    'comingSoon': '*और भाषाएँ जल्द आ रही हैं',
    'uiUpdateNote': '*UI भाषा भविष्य में अपडेट होगी।',
    'dailyReview': 'दैनिक समीक्षा',
    'jungleAdventure': 'जंगल साहसिक',
    'islandColors': 'द्वीप के रंग',
    'numbers': 'संख्याएँ',
    'nature': 'प्रकृति',
    'feelings': 'भावनाएँ',
    'colors': 'रंग',
    'animals': 'जानवर',
    'family': 'परिवार',
    'bodyParts': 'शरीर के अंग',
    'things': 'चीज़ें',
    'magicWords': 'जादुई शब्द',
    'games': 'खेल',
    'community': 'समुदाय',
    'voiceVault': 'ध्वनि संग्रह',
    'feedback': 'प्रतिक्रिया',
    'chatTranslate': 'चैट और अनुवाद',
    'commonPhrases': 'सामान्य वाक्यांश',
    'dialects': 'बोलियाँ',
    'search': 'खोजें',
    'quiz': 'प्रश्नोत्तरी',
    'progress': 'प्रगति',
    'generateReport': 'रिपोर्ट बनाएं',
    'levels': 'स्तर',
    'lessons': 'पाठ',
    'yourProgress': 'आपकी प्रगति',
    'totalSearches': 'कुल खोजें',
    'currentStreak': 'वर्तमान लकीर',
    'wordsLearned': 'सीखे गए शब्द',
    'recentQuiz': '📊 हालिया प्रश्नोत्तरी प्रदर्शन',
    'noQuizzes': 'अभी तक कोई प्रश्नोत्तरी पूरी नहीं हुई। सीखना शुरू करें!',
    'quizAccuracy': 'प्रश्नोत्तरी सटीकता',
    'tapMicToRecord': 'रिकॉर्ड करने के लिए माइक दबाएं',
    'recordingAudio': 'ऑडियो रिकॉर्ड हो रहा है... (ऑफ़लाइन)',
    'transcribingWhisper': 'विस्पर AI से लिखा जा रहा है...',
    'tapMicToAsk': 'कुछ पूछने के लिए माइक दबाएं!',
    'srsTitle': 'दैनिक समीक्षा',
    'again': 'फिर से',
    'hard': 'कठिन',
    'good': 'अच्छा',
    'easy': 'आसान',
    'noCardsToday': 'आज कोई कार्ड नहीं! 🎉',
    'showAnswer': 'उत्तर दिखाएं',
    'goBack': 'वापस जाएं',
    'days': 'दिन',
    'arTranslator': 'AR अनुवादक 🆕',
    'bookScanner': 'पुस्तक स्कैनर',
    'voiceTranslate': 'आवाज़ अनुवाद',
    'andamaneseBeta': 'अंडमानी ᴮᴱᵀᴬ',
    'natureHub': 'प्रकृति केंद्र',
    'oralHistory': 'मौखिक इतिहास',
    'tuhetKinship': 'तुहेट (नातेदारी)',
    'islandExplorer': 'द्वीप अन्वेषक',
    'memoryPalace': 'स्मृति महल',
    'exploreModules': 'मॉड्यूल खोजें',
    'seniorStudentAccess': 'वरिष्ठ छात्र पहुंच',
    'solveToEnter': 'प्रवेश करने के लिए इसे हल करें:\n12 + 15 = ?',
    'cancel': 'रद्द करें',
    'enter': 'प्रवेश करें',
    'incorrectAccessDenied': 'गलत। प्रवेश वर्जित 🚫',
    'classroomTools': 'कक्षा उपकरण',
    'learningTools': 'सीखने के उपकरण',
    'communitySettings': 'समुदाय और सेटिंग्स',
    'dictEditor': 'शब्दकोश संपादक',
    'importVocab': 'शब्दावली आयात करें',
    'textTranslator': 'पाठ अनुवादक',
    'culture': 'संस्कृति',
    'certification': 'प्रमाणन',
    'quizMode': 'क्विज़ मोड',
    'srsAnalytics': 'SRS विश्लेषिकी',
    'dialectComparison': 'बोली की तुलना',
    'islandGis': 'द्वीप GIS',
    'tuhetMapper': 'तुहेट मैपर',
    'villageHub': 'ग्राम केंद्र',
    'whisperPro': 'विस्पर प्रो',
    'betaChat': 'बीटा चैट',
    'exportVocab': 'शब्दावली निर्यात करें',
    'dailyWord': 'आज का शब्द',

    // Student Dashboard UI
    'omniBroadcast': 'ओम्नी प्रसारण',
    'hindiTranslator': 'हिंदी\nअनुवादक',
    'tamilTranslator': 'तमिल\nअनुवादक',
    'bengaliTranslator': 'बंगाली\nअनुवादक',
    'teluguTranslator': 'तेलुगू\nअनुवादक',
    'malayalamTranslator': 'मलयालम\nअनुवादक',
    'aiSetup': 'AI सेटअप',
    'sectionSoundWave': 'ध्वनि तरंग',
    'sectionMyProgress': 'मेरी प्रगति',
    'sectionMyBadges': 'मेरे बैज',
    'sectionLetsLearn': 'चलो सीखते हैं!',
    'dailyMission': 'दैनिक मिशन',
    'missionHint': 'AR स्कैनर या गेम्स से शब्द खोजें 🌟',
    'percentDone': 'पूरा!',
    'petHappySpeech': 'वाह! चलो सीखते हैं! 🌟',
    'streakLabel': 'लकीर',
    'starsLabel': 'सितारे',
    'levelLabel': 'स्तर',
    'missionLearnWords': '5 नए निकोबारी शब्द सीखो!',
    'missionPlayGames': '2 शब्द खेल खेलो!',
    'missionScanAR': 'AR से 3 चीज़ें स्कैन करो!',
    'missionRecordVoice': '3 आवाज़ अनुवाद रिकॉर्ड करो!',
    'missionBodyQuiz': '1 शरीर भाग क्विज़ पूरा करो!',
    'missionAnimals': '4 जानवर शब्द खोजो!',
    'missionNature': '3 प्रकृति शब्द सीखो!',
    'missionNumbers': '5 संख्या शब्द अभ्यास करो!',
    'missionStories': '1 मौखिक कहानी सुनो!',
    'missionColors': '4 रंग शब्द अनुवाद करो!',
  };

  // ═══════════════════════════════════════════════
  // TAMIL (தமிழ்)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _ta = {
    'appName': 'ஸ்பீச்மேட்',
    'tagline': 'மொழி தடைகள் முடியும் இடம்',
    'youAre': 'நீங்கள்:',
    'student': 'மாணவர்',
    'teacher': 'ஆசிரியர்',
    'continueBtn': 'தொடரவும்',
    'guest': 'விருந்தினர்',
    'selectLanguage': 'மொழிபெயர்க்க/கற்க ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
    'selectAppLanguage': 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    'comingSoon': '*மேலும் மொழிகள் விரைவில்',
    'uiUpdateNote': '*UI உரைகள் எதிர்கால புதுப்பிப்பில் மாற்றப்படும்.',
    'dailyReview': 'தினசரி மதிப்பாய்வு',
    'jungleAdventure': 'காட்டு சாகசம்',
    'islandColors': 'தீவு நிறங்கள்',
    'numbers': 'எண்கள்',
    'nature': 'இயற்கை',
    'feelings': 'உணர்வுகள்',
    'colors': 'நிறங்கள்',
    'animals': 'விலங்குகள்',
    'family': 'குடும்பம்',
    'bodyParts': 'உடல் பாகங்கள்',
    'things': 'பொருட்கள்',
    'magicWords': 'மந்திர வார்த்தைகள்',
    'games': 'விளையாட்டுகள்',
    'community': 'சமூகம்',
    'voiceVault': 'குரல் பெட்டகம்',
    'feedback': 'கருத்து',
    'chatTranslate': 'அரட்டை & மொழிபெயர்க்க',
    'commonPhrases': 'பொதுவான சொற்றொடர்கள்',
    'dialects': 'வட்டார மொழிகள்',
    'search': 'தேடு',
    'quiz': 'வினாடி வினா',
    'progress': 'முன்னேற்றம்',
    'generateReport': 'அறிக்கை உருவாக்கு',
    'levels': 'நிலைகள்',
    'lessons': 'பாடங்கள்',
    'yourProgress': 'உங்கள் முன்னேற்றம்',
    'totalSearches': 'மொத்த தேடல்கள்',
    'currentStreak': 'தற்போதைய தொடர்',
    'wordsLearned': 'கற்ற சொற்கள்',
    'recentQuiz': '📊 சமீபத்திய வினாடி வினா செயல்திறன்',
    'noQuizzes': 'இன்னும் வினாடி வினா முடிக்கவில்லை. கற்கத் தொடங்குங்கள்!',
    'quizAccuracy': 'வினாடி வினா துல்லியம்',
    'tapMicToRecord': 'பதிவு செய்ய மைக்கை தட்டவும்',
    'recordingAudio': 'ஒலி பதிவாகிறது... (ஆஃப்லைன்)',
    'transcribingWhisper': 'விஸ்பர் AI மூலம் எழுதப்படுகிறது...',
    'tapMicToAsk': 'கேட்க மைக்கை தட்டவும்!',
    'srsTitle': 'தினசரி மதிப்பாய்வு',
    'again': 'மீண்டும்',
    'hard': 'கடினம்',
    'good': 'நல்லது',
    'easy': 'எளிது',
    'noCardsToday': 'இன்று அட்டைகள் இல்லை! 🎉',
    'showAnswer': 'பதிலைக் காட்டு',
    'goBack': 'திரும்பிச் செல்',
    'days': 'நாட்கள்',
    'arTranslator': 'AR மொழிபெயர்ப்பாளர் 🆕',
    'bookScanner': 'புத்தக ஸ்கேனர்',
    'voiceTranslate': 'குரல் மொழிபெயர்ப்பு',
    'andamaneseBeta': 'அந்தமானீஸ் ᴮᴱᵀᴬ',
    'natureHub': 'இயற்கை மையம்',
    'oralHistory': 'வாய்மொழி வரலாறு',
    'tuhetKinship': 'துஹெட் (உறவினர்கள்)',
    'islandExplorer': 'தீவு ஆய்வாளர்',
    'memoryPalace': 'நினைவக அரண்மனை',
    'exploreModules': 'தொகுதிகளை ஆராயுங்கள்',
    'seniorStudentAccess': 'மூத்த மாணவர் அணுகல்',
    'solveToEnter': 'உள்ளே நுழைய இதைத் தீர்க்கவும்:\n12 + 15 = ?',
    'cancel': 'ரத்துசெய்',
    'enter': 'உள்ளிடவும்',
    'incorrectAccessDenied': 'தவறு. அணுகல் மறுக்கப்பட்டது 🚫',
    'classroomTools': 'வகுப்பறை கருவிகள்',
    'learningTools': 'கற்றல் கருவிகள்',
    'communitySettings': 'சமூகம் & அமைப்புகள்',
    'dictEditor': 'அகராதி ஆசிரியர்',
    'importVocab': 'சொற்களஞ்சியத்தை இறக்குமதி செய்',
    'textTranslator': 'உரை மொழிபெயர்ப்பாளர்',
    'culture': 'கலாச்சாரம்',
    'certification': 'சான்றிதழ்',
    'quizMode': 'வினாடி வினா முறை',
    'srsAnalytics': 'SRS பகுப்பாய்வு',
    'dialectComparison': 'வட்டார மொழி ஒப்பீடு',
    'islandGis': 'தீவு GIS',
    'tuhetMapper': 'துஹெட் மேப்பர்',
    'villageHub': 'கிராம மையம்',
    'whisperPro': 'விஸ்பர் ப்ரோ',
    'betaChat': 'பீட்டா அரட்டை',
    'exportVocab': 'சொற்களஞ்சியத்தை ஏற்றுமதி செய்',
    'dailyWord': 'இன்றைய சொல்',

    // Student Dashboard UI
    'omniBroadcast': 'ஆம்னி ஒளிபரப்பு',
    'hindiTranslator': 'இந்தி\nமொழிபெயர்ப்பாளர்',
    'tamilTranslator': 'தமிழ்\nமொழிபெயர்ப்பாளர்',
    'bengaliTranslator': 'வங்காள\nமொழிபெயர்ப்பாளர்',
    'teluguTranslator': 'தெலுங்கு\nமொழிபெயர்ப்பாளர்',
    'malayalamTranslator': 'மலையாள\nமொழிபெயர்ப்பாளர்',
    'aiSetup': 'AI அமைவு',
    'sectionSoundWave': 'ஒலி அலை',
    'sectionMyProgress': 'எனது முன்னேற்றம்',
    'sectionMyBadges': 'எனது பேட்ஜ்கள்',
    'sectionLetsLearn': 'கற்கலாம்!',
    'dailyMission': 'தினசரி பணி',
    'missionHint': 'சொற்களைக் கண்டறிய AR ஸ்கேனர் அல்லது கேம்களைப் பயன்படுத்தவும் 🌟',
    'percentDone': 'முடிந்தது!',
    'petHappySpeech': 'கற்கலாம்! 🌟',
    'streakLabel': 'தொடர்ச்சி',
    'starsLabel': 'நட்சத்திரங்கள்',
    'levelLabel': 'நிலை',
    'missionLearnWords': '5 புதிய நிக்கோபாரி சொற்களைக் கற்றுக்கொள்!',
    'missionPlayGames': '2 சொல் விளையாட்டுகளை விளையாடு!',
    'missionScanAR': 'AR மூலம் 3 பொருட்களை ஸ்கேன் செய்!',
    'missionRecordVoice': '3 குரல் மொழிபெயர்ப்புகளைப் பதிவு செய்!',
    'missionBodyQuiz': '1 உடல் பாக வினாடி வினாவை முடி!',
    'missionAnimals': '4 விலங்கு சொற்களைக் கண்டறி!',
    'missionNature': '3 இயற்கை சொற்களைக் கற்றுக்கொள்!',
    'missionNumbers': '5 எண் சொற்களைப் பயிற்சி செய்!',
    'missionStories': '1 வாய்வழி கதையைக் கேள்!',
    'missionColors': '4 நிற சொற்களை மொழிபெயர்க்கவும்!',
  };

  // ═══════════════════════════════════════════════
  // MALAYALAM (മലയാളം)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _ml = {
    'appName': 'സ്പീച്ച്‌മേറ്റ്',
    'tagline': 'ഭാഷാ തടസ്സങ്ങൾ അവസാനിക്കുന്നിടം',
    'youAre': 'നിങ്ങൾ:',
    'student': 'വിദ്യാർത്ഥി',
    'teacher': 'അധ്യാപകൻ',
    'continueBtn': 'തുടരുക',
    'guest': 'അതിഥി',
    'selectLanguage': 'വിവർത്തനം/പഠിക്കാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    'selectAppLanguage': 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
    'comingSoon': '*കൂടുതൽ ഭാഷകൾ ഉടൻ',
    'uiUpdateNote': '*UI ടെക്‌സ്‌റ്റുകൾ ഭാവിയിലെ അപ്‌ഡേറ്റിൽ മാറും.',
    'dailyReview': 'ദൈനംദിന അവലോകനം',
    'jungleAdventure': 'കാട്ടിലെ സാഹസികത',
    'islandColors': 'ദ്വീപ് നിറങ്ങൾ',
    'numbers': 'സംഖ്യകൾ',
    'nature': 'പ്രകൃതി',
    'feelings': 'വികാരങ്ങൾ',
    'colors': 'നിറങ്ങൾ',
    'animals': 'മൃഗങ്ങൾ',
    'family': 'കുടുംബം',
    'bodyParts': 'ശരീര ഭാഗങ്ങൾ',
    'things': 'വസ്‌തുക്കൾ',
    'magicWords': 'മാന്ത്രിക വാക്കുകൾ',
    'games': 'കളികൾ',
    'community': 'കമ്മ്യൂണിറ്റി',
    'voiceVault': 'ശബ്ദ ശേഖരം',
    'feedback': 'ഫീഡ്‌ബാക്ക്',
    'chatTranslate': 'ചാറ്റ് & വിവർത്തനം',
    'commonPhrases': 'സാധാരണ ശൈലികൾ',
    'dialects': 'ഉപഭാഷകൾ',
    'search': 'തിരയുക',
    'quiz': 'ക്വിസ്',
    'progress': 'പുരോഗതി',
    'generateReport': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    'levels': 'ലെവലുകൾ',
    'lessons': 'പാഠങ്ങൾ',
    'yourProgress': 'നിങ്ങളുടെ പുരോഗതി',
    'totalSearches': 'ആകെ തിരയലുകൾ',
    'currentStreak': 'നിലവിലെ സ്‌ട്രീക്ക്',
    'wordsLearned': 'പഠിച്ച വാക്കുകൾ',
    'recentQuiz': '📊 സമീപകാല ക്വിസ് പ്രകടനം',
    'noQuizzes': 'ഇതുവരെ ക്വിസ് പൂർത്തിയാക്കിയിട്ടില്ല. പഠിക്കാൻ തുടങ്ങൂ!',
    'quizAccuracy': 'ക്വിസ് കൃത്യത',
    'tapMicToRecord': 'റെക്കോർഡ് ചെയ്യാൻ മൈക്ക് ടാപ്പ് ചെയ്യുക',
    'recordingAudio': 'ഓഡിയോ റെക്കോർഡ് ചെയ്യുന്നു... (ഓഫ്‌ലൈൻ)',
    'transcribingWhisper': 'വിസ്‌പർ AI ഉപയോഗിച്ച് ട്രാൻസ്ക്രൈബ് ചെയ്യുന്നു...',
    'tapMicToAsk': 'എന്തെങ്കിലും ചോദിക്കാൻ മൈക്ക് ടാപ്പ് ചെയ്യുക!',
    'srsTitle': 'ദൈനംദിന അവലോകനം',
    'again': 'വീണ്ടും',
    'hard': 'കഠിനം',
    'good': 'നല്ലത്',
    'easy': 'എളുപ്പം',
    'noCardsToday': 'ഇന്ന് കാർഡുകൾ ഇല്ല! 🎉',
    'showAnswer': 'ഉത്തരം കാണിക്കുക',
    'goBack': 'തിരിച്ചുപോകുക',
    'days': 'ദിവസങ്ങൾ',
    'arTranslator': 'AR വിവർത്തകൻ 🆕',
    'bookScanner': 'ബുക്ക് സ്കാനർ',
    'voiceTranslate': 'വോയ്‌സ് വിവർത്തനം',
    'andamaneseBeta': 'ആൻഡമാനീസ് ᴮᴱᵀᴬ',
    'natureHub': 'പ്രകൃതി ഹബ്',
    'oralHistory': 'വാമൊഴി ചരിത്രം',
    'tuhetKinship': 'തുഹെറ്റ് (ബന്ധുത്വം)',
    'islandExplorer': 'ദ്വീപ് പര്യവേക്ഷകൻ',
    'memoryPalace': 'ഓർമ്മ കൊട്ടാരം',
    'exploreModules': 'മൊഡ്യൂളുകൾ പര്യവേക്ഷണം ചെയ്യുക',
    'seniorStudentAccess': 'സീനിയർ വിദ്യാർത്ഥി പ്രവേശനം',
    'solveToEnter': 'പ്രവേശിക്കാൻ ഇത് പരിഹരിക്കുക:\n12 + 15 = ?',
    'cancel': 'റദ്ദാക്കുക',
    'enter': 'പ്രവേശിക്കുക',
    'incorrectAccessDenied': 'തെറ്റാണ്. പ്രവേശനം നിഷേധിച്ചു 🚫',
    'classroomTools': 'ക്ലാസ്റൂം ടൂളുകൾ',
    'learningTools': 'പഠന ടൂളുകൾ',
    'communitySettings': 'കമ്മ്യൂണിറ്റിയും ക്രമീകരണങ്ങളും',
    'dictEditor': 'നിഘണ്ടു എഡിറ്റർ',
    'importVocab': 'പദാവലി ഇറക്കുമതി ചെയ്യുക',
    'textTranslator': 'ടെക്സ്റ്റ് വിവർത്തകൻ',
    'culture': 'സംസ്കാരം',
    'certification': 'സർട്ടിഫിക്കേഷൻ',
    'quizMode': 'ക്വിസ് മോഡ്',
    'srsAnalytics': 'SRS അനലിറ്റിക്സ്',
    'dialectComparison': 'ഉപഭാഷാ താരതമ്യം',
    'islandGis': 'ദ്വീപ് GIS',
    'tuhetMapper': 'തുഹെറ്റ് മാപ്പർ',
    'villageHub': 'വില്ലേജ് ഹബ്',
    'whisperPro': 'വിസ്പർ പ്രോ',
    'betaChat': 'ബീറ്റാ ചാറ്റ്',
    'exportVocab': 'പദാവലി കയറ്റുമതി ചെയ്യുക',
    'dailyWord': 'ഇന്നത്തെ വാക്ക്',

    // Student Dashboard UI
    'omniBroadcast': 'ഓമ്‌നി സംപ്രേക്ഷണം',
    'hindiTranslator': 'ഹിന്ദി\nവിവർത്തകൻ',
    'tamilTranslator': 'തമിഴ്\nവിവർത്തകൻ',
    'bengaliTranslator': 'ബംഗാളി\nവിവർത്തകൻ',
    'teluguTranslator': 'തെലുങ്ക്\nവിവർത്തകൻ',
    'malayalamTranslator': 'മലയാളം\nവിവർത്തകൻ',
    'aiSetup': 'AI സജ്ജീകരണം',
    'sectionSoundWave': 'ശബ്ദ തരംഗം',
    'sectionMyProgress': 'എന്റെ പുരോഗതി',
    'sectionMyBadges': 'എന്റെ ബാഡ്ജുകൾ',
    'sectionLetsLearn': 'നമുക്ക് പഠിക്കാം!',
    'dailyMission': 'പ്രതിദിന ലക്ഷ്യം',
    'missionHint': 'വാക്കുകൾ കണ്ടെത്താൻ AR സ്കാനർ അല്ലെങ്കിൽ ഗെയിമുകൾ ഉപയോഗിക്കുക 🌟',
    'percentDone': 'പൂർത്തിയായി!',
    'petHappySpeech': 'നമുക്ക് പഠിക്കാം! 🌟',
    'streakLabel': 'തുടർച്ച',
    'starsLabel': 'നക്ഷത്രങ്ങൾ',
    'levelLabel': 'നില',
    'missionLearnWords': '5 പുതിയ നിക്കോബാരി വാക്കുകൾ പഠിക്കുക!',
    'missionPlayGames': '2 വാക്ക് ഗെയിമുകൾ കളിക്കുക!',
    'missionScanAR': 'AR ഉപയോഗിച്ച് 3 വസ്തുക്കൾ സ്കാൻ ചെയ്യുക!',
    'missionRecordVoice': '3 വോയ്സ് വിവർത്തനങ്ങൾ റെക്കോർഡ് ചെയ്യുക!',
    'missionBodyQuiz': '1 ശരീരഭാഗ ക്വിസ് പൂർത്തിയാക്കുക!',
    'missionAnimals': '4 മൃഗങ്ങളുടെ വാക്കുകൾ കണ്ടെത്തുക!',
    'missionNature': '3 പ്രകൃതി വാക്കുകൾ പഠിക്കുക!',
    'missionNumbers': '5 അക്ക വാക്കുകൾ പരിശീലിക്കുക!',
    'missionStories': '1 വാമൊഴി ചരിത്രം കേൾക്കുക!',
    'missionColors': '4 നിറങ്ങളുടെ വാക്കുകൾ വിവർത്തനം ചെയ്യുക!',
  };

  // ═══════════════════════════════════════════════
  // BENGALI (বাংলা)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _bn = {
    'appName': 'স্পিচমেট',
    'tagline': 'যেখানে ভাষার বাধা শেষ হয়',
    'youAre': 'আপনি হলেন:',
    'student': 'শিক্ষার্থী',
    'teacher': 'শিক্ষক',
    'continueBtn': 'চালিয়ে যান',
    'guest': 'অতিথি',
    'selectLanguage': 'অনুবাদ/শেখার জন্য একটি ভাষা নির্বাচন করুন',
    'selectAppLanguage': 'অ্যাপের ভাষা নির্বাচন করুন',
    'comingSoon': '*আরও ভাষা শীঘ্রই আসছে',
    'uiUpdateNote': '*UI পাঠ্য ভবিষ্যতে আপডেট হবে।',
    'dailyReview': 'দৈনিক পর্যালোচনা',
    'jungleAdventure': 'জঙ্গল অ্যাডভেঞ্চার',
    'islandColors': 'দ্বীপের রঙ',
    'numbers': 'সংখ্যা',
    'nature': 'প্রকৃতি',
    'feelings': 'অনুভূতি',
    'colors': 'রঙ',
    'animals': 'পশুপাখি',
    'family': 'পরিবার',
    'bodyParts': 'শরীরের অংশ',
    'things': 'জিনিসপত্র',
    'magicWords': 'জাদু শব্দ',
    'games': 'খেলা',
    'community': 'সম্প্রদায়',
    'voiceVault': 'ভয়েস ভল্ট',
    'feedback': 'মতামত',
    'chatTranslate': 'চ্যাট ও অনুবাদ',
    'commonPhrases': 'সাধারণ বাক্যাংশ',
    'dialects': 'উপভাষা',
    'search': 'অনুসন্ধান',
    'quiz': 'কুইজ',
    'progress': 'অগ্রগতি',
    'generateReport': 'রিপোর্ট তৈরি করুন',
    'levels': 'স্তর',
    'lessons': 'পাঠ',
    'yourProgress': 'আপনার অগ্রগতি',
    'totalSearches': 'মোট অনুসন্ধান',
    'currentStreak': 'বর্তমান ধারা',
    'wordsLearned': 'শেখা শব্দ',
    'recentQuiz': '📊 সাম্প্রতিক কুইজ পারফরম্যান্স',
    'noQuizzes': 'এখনও কোনো কুইজ সম্পন্ন হয়নি। শেখা শুরু করুন!',
    'quizAccuracy': 'কুইজ নির্ভুলতা',
    'tapMicToRecord': 'রেকর্ড করতে মাইক ট্যাপ করুন',
    'recordingAudio': 'অডিও রেকর্ড হচ্ছে... (অফলাইন)',
    'transcribingWhisper': 'হুইসপার AI দিয়ে লেখা হচ্ছে...',
    'tapMicToAsk': 'কিছু জিজ্ঞাসা করতে মাইক ট্যাপ করুন!',
    'srsTitle': 'দৈনিক পর্যালোচনা',
    'again': 'আবার',
    'hard': 'কঠিন',
    'good': 'ভালো',
    'easy': 'সহজ',
    'noCardsToday': 'আজ কোনো কার্ড নেই! 🎉',
    'showAnswer': 'উত্তর দেখান',
    'goBack': 'ফিরে যান',
    'days': 'দিন',
    'arTranslator': 'AR অনুবাদক 🆕',
    'bookScanner': 'বই স্ক্যানার',
    'voiceTranslate': 'ভয়েস অনুবাদ',
    'andamaneseBeta': 'আন্দামানি ᴮᴱᵀᴬ',
    'natureHub': 'প্রকৃতি হাব',
    'oralHistory': 'মৌখিক ইতিহাস',
    'tuhetKinship': 'টুহেট (আত্মীয়তা)',
    'islandExplorer': 'দ্বীপ এক্সপ্লোরার',
    'memoryPalace': 'মেমরি প্যালেস',
    'exploreModules': 'মডিউল অন্বেষণ করুন',
    'seniorStudentAccess': 'সিনিয়র ছাত্র অ্যাক্সেস',
    'solveToEnter': 'প্রবেশ করতে এটি সমাধান করুন:\n12 + 15 = ?',
    'cancel': 'বাতিল করুন',
    'enter': 'প্রবেশ করুন',
    'incorrectAccessDenied': 'ভুল। অ্যাক্সেস প্রত্যাখ্যান করা হয়েছে 🚫',
    'classroomTools': 'শ্রেণীকক্ষ সরঞ্জাম',
    'learningTools': 'শেখার সরঞ্জাম',
    'communitySettings': 'সম্প্রদায় এবং সেটিংস',
    'dictEditor': 'অভিধান সম্পাদক',
    'importVocab': 'শব্দভাণ্ডার আমদানি করুন',
    'textTranslator': 'পাঠ্য অনুবাদক',
    'culture': 'সংস্কৃতি',
    'certification': 'সার্টিফিকেশন',
    'quizMode': 'কুইজ মোড',
    'srsAnalytics': 'SRS অ্যানালিটিক্স',
    'dialectComparison': 'উপভাষা তুলনা',
    'islandGis': 'দ্বীপ GIS',
    'tuhetMapper': 'টুহেট ম্যাপার',
    'villageHub': 'গ্রাম হাব',
    'whisperPro': 'হুইসপার প্রো',
    'betaChat': 'বিটা চ্যাট',
    'exportVocab': 'শব্দভাণ্ডার রপ্তানি করুন',
    'dailyWord': 'আজকের শব্দ',

    // Student Dashboard UI
    'omniBroadcast': 'ওমনি সম্প্রচার',
    'hindiTranslator': 'হিন্দি\nঅনুবাদক',
    'tamilTranslator': 'তামিল\nঅনুবাদক',
    'bengaliTranslator': 'বাংলা\nঅনুবাদক',
    'teluguTranslator': 'তেলেগু\nঅনুবাদক',
    'malayalamTranslator': 'মালায়ালম\nঅনুবাদক',
    'aiSetup': 'AI সেটআপ',
    'sectionSoundWave': 'শব্দ তরঙ্গ',
    'sectionMyProgress': 'আমার অগ্রগতি',
    'sectionMyBadges': 'আমার ব্যাজ',
    'sectionLetsLearn': 'চল শিখি!',
    'dailyMission': 'দৈনিক মিশন',
    'missionHint': 'শব্দ খুঁজতে AR স্ক্যানার বা গেম ব্যবহার করুন 🌟',
    'percentDone': 'সম্পন্ন!',
    'petHappySpeech': 'চল শিখি! 🌟',
    'streakLabel': 'স্ট্রিক',
    'starsLabel': 'তারা',
    'levelLabel': 'স্তর',
    'missionLearnWords': '৫টি নতুন নিকোবরি শব্দ শিখুন!',
    'missionPlayGames': '২টি শব্দ গেম খেলুন!',
    'missionScanAR': 'AR দিয়ে ৩টি বস্তু স্ক্যান করুন!',
    'missionRecordVoice': '৩টি ভয়েস অনুবাদ রেকর্ড করুন!',
    'missionBodyQuiz': '১টি শরীরের অঙ্গ কুইজ সম্পন্ন করুন!',
    'missionAnimals': '৪টি প্রাণীর শব্দ খুঁজুন!',
    'missionNature': '৩টি প্রকৃতির শব্দ শিখুন!',
    'missionNumbers': '৫টি সংখ্যার শব্দ অনুশীলন করুন!',
    'missionStories': '১টি মৌখিক ইতিহাস শুনুন!',
    'missionColors': '৪টি রঙের শব্দ অনুবাদ করুন!',
  };

  // ═══════════════════════════════════════════════
  // TELUGU (తెలుగు)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _te = {
    'appName': 'స్పీచ్‌మేట్',
    'tagline': 'భాషా అడ్డంకులు ముగిసే చోటు',
    'youAre': 'మీరు:',
    'student': 'విద్యార్థి',
    'teacher': 'ఉపాధ్యాయుడు',
    'continueBtn': 'కొనసాగించు',
    'guest': 'అతిథి',
    'selectLanguage': 'అనువాదం/నేర్చుకోవడానికి ఒక భాషను ఎంచుకోండి',
    'selectAppLanguage': 'యాప్ భాషను ఎంచుకోండి',
    'comingSoon': '*మరిన్ని భాషలు త్వరలో',
    'uiUpdateNote': '*UI వచనాలు భవిష్యత్ అప్‌డేట్‌లో మారుతాయి.',
    'dailyReview': 'రోజువారీ సమీక్ష',
    'jungleAdventure': 'అడవి సాహసం',
    'islandColors': 'దీవి రంగులు',
    'numbers': 'సంఖ్యలు',
    'nature': 'ప్రకృతి',
    'feelings': 'భావాలు',
    'colors': 'రంగులు',
    'animals': 'జంతువులు',
    'family': 'కుటుంబం',
    'bodyParts': 'శరీర భాగాలు',
    'things': 'వస్తువులు',
    'magicWords': 'మంత్ర పదాలు',
    'games': 'ఆటలు',
    'community': 'సమాజం',
    'voiceVault': 'వాయిస్ వాల్ట్',
    'feedback': 'అభిప్రాయం',
    'chatTranslate': 'చాట్ & అనువాదం',
    'commonPhrases': 'సాధారణ పదబంధాలు',
    'dialects': 'మాండలికాలు',
    'search': 'వెతుకు',
    'quiz': 'క్విజ్',
    'progress': 'పురోగతి',
    'generateReport': 'రిపోర్ట్ తయారు చేయండి',
    'levels': 'స్థాయిలు',
    'lessons': 'పాఠాలు',
    'yourProgress': 'మీ పురోగతి',
    'totalSearches': 'మొత్తం శోధనలు',
    'currentStreak': 'ప్రస్తుత స్ట్రీక్',
    'wordsLearned': 'నేర్చుకున్న పదాలు',
    'recentQuiz': '📊 ఇటీవలి క్విజ్ ప్రదర్శన',
    'noQuizzes': 'ఇంకా క్విజ్‌లు పూర్తి కాలేదు. నేర్చుకోవడం ప్రారంభించండి!',
    'quizAccuracy': 'క్విజ్ ఖచ్చితత్వం',
    'tapMicToRecord': 'రికార్డ్ చేయడానికి మైక్ నొక్కండి',
    'recordingAudio': 'ఆడియో రికార్డ్ అవుతోంది... (ఆఫ్‌లైన్)',
    'transcribingWhisper': 'విస్పర్ AI ద్వారా రాయబడుతోంది...',
    'tapMicToAsk': 'ఏదైనా అడగడానికి మైక్ నొక్కండి!',
    'srsTitle': 'రోజువారీ సమీక్ష',
    'again': 'మళ్ళీ',
    'hard': 'కష్టం',
    'good': 'బాగుంది',
    'easy': 'సులభం',
    'noCardsToday': 'ఈరోజు కార్డులు లేవు! 🎉',
    'showAnswer': 'సమాధానం చూపించు',
    'goBack': 'వెనక్కి వెళ్ళు',
    'days': 'రోజులు',
    'arTranslator': 'AR అనువాదకుడు 🆕',
    'bookScanner': 'పుస్తక స్కానర్',
    'voiceTranslate': 'వాయిస్ అనువాదం',
    'andamaneseBeta': 'అండమానీస్ ᴮᴱᵀᴬ',
    'natureHub': 'ప్రకৃতি హబ్',
    'oralHistory': 'మౌఖిక చరిత్ర',
    'tuhetKinship': 'టుహెట్ (బంధుత్వం)',
    'islandExplorer': 'ద్వీపం అన్వేషకుడు',
    'memoryPalace': 'మెమరీ ప్యాలెస్',
    'exploreModules': 'మాడ్యూళ్లను అన్వేషించండి',
    'seniorStudentAccess': 'సీనియర్ విద్యార్థి యాక్సెస్',
    'solveToEnter': 'ప్రవేశించడానికి దీన్ని పరిష్కరించండి:\n12 + 15 = ?',
    'cancel': 'రద్దు చేయి',
    'enter': 'ప్రవేశించు',
    'incorrectAccessDenied': 'తప్పు. యాక్సెస్ తిరస్కరించబడింది 🚫',
    'classroomTools': 'తరగతి గది సాధనాలు',
    'learningTools': 'అభ్యాస సాధనాలు',
    'communitySettings': 'సంఘం & సెట్టింగ్‌లు',
    'dictEditor': 'నిఘంటువు ఎడిటర్',
    'importVocab': 'పదజాలాన్ని దిగుమతి చేయండి',
    'textTranslator': 'వచన అనువాదకుడు',
    'culture': 'సంస్కృతి',
    'certification': 'ధృవీకరణ',
    'quizMode': 'క్విజ్ మోడ్',
    'srsAnalytics': 'SRS విశ్లేషణలు',
    'dialectComparison': 'మాండలికం పోలిక',
    'islandGis': 'ద్వీపం GIS',
    'tuhetMapper': 'టుహెట్ మ్యాపర్',
    'villageHub': 'విలేజ్ హబ్',
    'whisperPro': 'విస్పర్ ప్రో',
    'betaChat': 'బీటా చాట్',
    'exportVocab': 'పదజాలాన్ని ఎగుమతి చేయండి',
    'dailyWord': 'నేటి పదం',

    // Student Dashboard UI
    'omniBroadcast': 'ఓమ్ని ప్రసారం',
    'hindiTranslator': 'హిందీ\nఅనువాదకుడు',
    'tamilTranslator': 'తమిళ\nఅనువాదకుడు',
    'bengaliTranslator': 'బెంగాలీ\nఅనువాదకుడు',
    'teluguTranslator': 'తెలుగు\nఅనువాదకుడు',
    'malayalamTranslator': 'మలయాళ\nఅనువాదకుడు',
    'aiSetup': 'AI సెటప్',
    'sectionSoundWave': 'ధ్వని తరంగం',
    'sectionMyProgress': 'నా పురోగతి',
    'sectionMyBadges': 'నా బ్యాడ్జీలు',
    'sectionLetsLearn': 'నేర్చుకుందాం!',
    'dailyMission': 'రోజువారీ లక్ష్యం',
    'missionHint': 'పదాలను కనుగొనడానికి AR స్కానర్ లేదా ఆటలను ఉపయోగించండి 🌟',
    'percentDone': 'పూర్తయింది!',
    'petHappySpeech': 'నేర్చుకుందాం! 🌟',
    'streakLabel': 'పరంపర',
    'starsLabel': 'నక్షత్రాలు',
    'levelLabel': 'స్థాయి',
    'missionLearnWords': '5 కొత్త నికోబారీ పదాలను నేర్చుకోండి!',
    'missionPlayGames': '2 పదాల ఆటలను ఆడండి!',
    'missionScanAR': 'AR తో 3 వస్తువులను స్కాన్ చేయండి!',
    'missionRecordVoice': '3 వాయిస్ అనువాదాలను రికార్డ్ చేయండి!',
    'missionBodyQuiz': '1 శరీర భాగాల క్విజ్‌ను పూర్తి చేయండి!',
    'missionAnimals': '4 జంతువుల పదాలను కనుగొనండి!',
    'missionNature': '3 ప్రకృతి పదాలను నేర్చుకోండి!',
    'missionNumbers': '5 సంఖ్య పదాలను ప్రాక్టీస్ చేయండి!',
    'missionStories': '1 మౌఖిక చరిత్రను వినండి!',
    'missionColors': '4 రంగు పదాలను అనువదించండి!',
  };

  // ═══════════════════════════════════════════════
  // GREAT ANDAMANESE (gn)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _gn = {
    'appName': 'Speecho', // Placeholders until native community consensus
    'tagline': 'Julu boi-jio',
    'youAre': 'Ngiyo:',
    'student': 'Utire',
    'teacher': 'Oko-jumu',
    'continueBtn': 'Kato',
    'guest': 'Ep',
    'selectLanguage': 'Julu aka',
    'selectAppLanguage': 'Aka-julu yop',
    'dailyReview': 'Tare-tare',
    'jungleAdventure': 'Erem-toro',
    'islandColors': 'Tobo-chiro',
    'community': 'Oko-tolo',
    'voiceVault': 'Puchh-toro',
    'search': 'Koyo',
    'quiz': 'Boi-toro',
    'yourProgress': 'Ngiyo kolo',
    'tapMicToRecord': 'Mic e-koyo',
    'recordingAudio': 'Puchh...',
    'srsTitle': 'Tare',
    'showAnswer': 'E-koyo',
    'goBack': 'Tech-chi',
    'audioFirstDash': 'Puchh-Julu', // Audio-First Mode
    'arTranslator': 'AR E-koyo 🆕',
    'bookScanner': 'Puchh E-koyo',
    'voiceTranslate': 'Puchh E-koyo',
    'andamaneseBeta': 'Aka-Jeru ᴮᴱᵀᴬ',
    'natureHub': 'Erem',
    'oralHistory': 'Tare',
    'tuhetKinship': 'Tuhet',
    'islandExplorer': 'Tobo E-koyo',
    'memoryPalace': 'Boi-jio',
    'exploreModules': 'E-koyo',
    'seniorStudentAccess': 'Utire Kolo',
    'solveToEnter': '12 + 15 = ?',
    'cancel': 'Tech-chi',
    'enter': 'Kato',
    'incorrectAccessDenied': 'Tech-chi 🚫',
    'classroomTools': 'Oko-jumu Boi',
    'learningTools': 'Utire Boi',
    'communitySettings': 'Oko-tolo',
    'dictEditor': 'E-koyo Boi',
    'importVocab': 'Boi E-koyo',
    'textTranslator': 'E-koyo',
    'culture': 'Oko-tolo',
    'certification': 'Kolo',
    'quizMode': 'Boi-toro',
    'srsAnalytics': 'Tare-tare',
    'dialectComparison': 'Aka E-koyo',
    'islandGis': 'Tobo GIS',
    'tuhetMapper': 'Tuhet E-koyo',
    'villageHub': 'Oko-tolo',
    'whisperPro': 'Puchh Pro',
    'betaChat': 'Puchh E-koyo',
    'exportVocab': 'Boi',
    'dailyWord': 'Tare',

    // Student Dashboard UI
    'omniBroadcast': 'Omni Puchh',
    'hindiTranslator': 'Hindi\nE-koyo',
    'tamilTranslator': 'Tamil\nE-koyo',
    'bengaliTranslator': 'Bengali\nE-koyo',
    'teluguTranslator': 'Telugu\nE-koyo',
    'malayalamTranslator': 'Malayalam\nE-koyo',
    'aiSetup': 'AI Boi',
    'sectionSoundWave': 'Puchh',
    'sectionMyProgress': 'Ngiyo Kolo',
    'sectionMyBadges': 'Ngiyo Boi',
    'sectionLetsLearn': 'Julu!',
    'dailyMission': 'Tare Boi',
    'missionHint': 'AR E-koyo boi 🌟',
    'percentDone': 'kato!',
    'petHappySpeech': 'Julu! 🌟',
    'streakLabel': 'Kato',
    'starsLabel': 'Boi',
    'levelLabel': 'Kolo',
    'missionLearnWords': '5 Julu!',
    'missionPlayGames': '2 Boi!',
    'missionScanAR': '3 AR!',
    'missionRecordVoice': '3 Puchh!',
    'missionBodyQuiz': '1 Boi-toro!',
    'missionAnimals': '4 Erem!',
    'missionNature': '3 Erem!',
    'missionNumbers': '5 Boi!',
    'missionStories': '1 Tare!',
    'missionColors': '4 Tobo-chiro!',
  };

  // ═══════════════════════════════════════════════
  // NICOBARESE - CAR (nc)
  // ═══════════════════════════════════════════════
  static final Map<String, String> _nc = {
    'appName': 'SpeechMate',
    'tagline': 'Rinön pö yök',
    'youAre': 'Cö:',
    'student': 'Kunö',
    'teacher': 'Ukuvöt',
    'continueBtn': 'Lökh',
    'guest': 'Kamyō',
    'selectLanguage': 'Hol yök',
    'selectAppLanguage': 'Hol yök app',
    'dailyReview': 'Inrē lūm',
    'jungleAdventure': 'Tōt',
    'islandColors': 'Pū-cö',
    'community': 'In-yū',
    'voiceVault': 'Ngō-in',
    'search': 'Hol',
    'quiz': 'U-in',
    'yourProgress': 'Cö lūm',
    'tapMicToRecord': 'Mic tōt',
    'recordingAudio': 'Ngō...',
    'srsTitle': 'Lūm',
    'showAnswer': 'Yök in',
    'goBack': 'Hol back',
    'audioFirstDash': 'Ngō-Inrē', // Audio-First Mode
    'arTranslator': 'AR Hol 🆕',
    'bookScanner': 'Lūm Hol',
    'voiceTranslate': 'Ngō Hol',
    'andamaneseBeta': 'Andamanese ᴮᴱᵀᴬ',
    'natureHub': 'Tōt',
    'oralHistory': 'Inrē lūm',
    'tuhetKinship': 'Tuhet',
    'islandExplorer': 'Pū-cö Hol',
    'memoryPalace': 'In-yū',
    'exploreModules': 'Hol',
    'seniorStudentAccess': 'Kunö In-yū',
    'solveToEnter': '12 + 15 = ?',
    'cancel': 'Hol back',
    'enter': 'Lökh',
    'incorrectAccessDenied': 'Hol back 🚫',
    'classroomTools': 'Ukuvöt Hol',
    'learningTools': 'Kunö Hol',
    'communitySettings': 'In-yū',
    'dictEditor': 'Hol lūm',
    'importVocab': 'Lūm In',
    'textTranslator': 'Hol',
    'culture': 'In-yū',
    'certification': 'Cö lūm',
    'quizMode': 'U-in',
    'srsAnalytics': 'Inrē lūm',
    'dialectComparison': 'Hol yök',
    'islandGis': 'Pū-cö GIS',
    'tuhetMapper': 'Tuhet Hol',
    'villageHub': 'In-yū',
    'whisperPro': 'Ngō Pro',
    'betaChat': 'Ngō Hol',
    'exportVocab': 'Lūm Out',
    'dailyWord': 'Inrē lūm',

    // Student Dashboard UI
    'omniBroadcast': 'Omni Inrē',
    'hindiTranslator': 'Hindi\nHol',
    'tamilTranslator': 'Tamil\nHol',
    'bengaliTranslator': 'Bengali\nHol',
    'teluguTranslator': 'Telugu\nHol',
    'malayalamTranslator': 'Malayalam\nHol',
    'aiSetup': 'AI U-in',
    'sectionSoundWave': 'Ngō-in',
    'sectionMyProgress': 'Cö lūm',
    'sectionMyBadges': 'Inrē cö',
    'sectionLetsLearn': 'Kunö!',
    'dailyMission': 'Inrē lūm',
    'missionHint': 'AR Hol lūm 🌟',
    'percentDone': 'lökh!',
    'petHappySpeech': 'Kunö! 🌟',
    'streakLabel': 'Lūm',
    'starsLabel': 'Inrē',
    'levelLabel': 'Cö',
    'missionLearnWords': '5 Kunö!',
    'missionPlayGames': '2 Tōt!',
    'missionScanAR': '3 AR!',
    'missionRecordVoice': '3 Ngō!',
    'missionBodyQuiz': '1 U-in!',
    'missionAnimals': '4 Pū-cö!',
    'missionNature': '3 Tōt!',
    'missionNumbers': '5 Lūm!',
    'missionStories': '1 Inrē lūm!',
    'missionColors': '4 Pū-cö!',
  };
}
